# Generated by Django 4.2.5 on 2023-10-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('task', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kanban',
            },
        ),
        migrations.CreateModel(
            name='Kanban_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField()),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.kanban')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kanban_user',
            },
        ),
        migrations.AddField(
            model_name='kanban',
            name='user',
            field=models.ManyToManyField(through='kanban.Kanban_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
