# Generated by Django 4.2.5 on 2023-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
