# Generated by Django 4.2.5 on 2023-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
    ]
